### ISSUE TITLE
improve or remove peerDependencies

### ISSUE THREAD

**Issue by shlomitc** [wix-incubator/unidriver#10]
current `peerDependencies` warns for not installing some packages, but they might not always be required in a consuming project
for example, some projects might not need `protractor`/`puppeteer`/both:
![image](https://user-images.githubusercontent.com/6093192/46547075-816f2680-c8d3-11e8-9239-f9525de063ee.png)

also `react` version might be problematic for react-16 users

**Comment by GabiGrin** [comment]
Sorry, missed this
@shlomitc  I agree, but wanted to avoid the overhead involved with splitting it.

opened #17 to address this
