### ISSUE TITLE
Enabling triggering of keyboard events

### ISSUE THREAD

**Issue by GabiGrin** [wix-incubator/unidriver#13]
There is an obvious need for triggering keyboard events using UniDriver.
After a great discussion with @nirdom we agreed that keyboard global.
UniDriver will expose a new method, `pressKey(context: UniDriver, key: KeyCode)` 

It will not be part of the unidriver api as the action of pressing a key is global. We still need the context to know what environment we're on and an entity we can use to trigger the event.

WDYT? should be be global, or a unidriver method?
❤️  - `pressKey(base.$('.nice-ui'), 13)`
🎉 - `base.$('.nice-ui').pressKey(13)`

@gavrielco  @shlomitc  @borisd9 @nirdom ?

**Comment by shlomitc** [comment]
I think that the second approach is more convenient, as you don't need to import additional functions/modules but might not make sense when it has a "global" effect.

In many cases, you would do some action and then press a key.
for example, click an input field and start pressing keys, click on a dropdown and navigate between items, click on a checkbox and tab through other checkboxes.

so maybe both should be exposed?

**Comment by GabiGrin** [comment]
@shlomitc thanks for the comment! the main motivation for it being global is that the action itself:
- always global, you never "press key on an element" - thus less confusing on it's real intentions
- we managed without it after 100+ drivers - thus hopefully the extra import is less of a problem

not sure about exposing both though
