### ISSUE TITLE
incorrect work of attr method at puppeteer unidriver

### ISSUE THREAD

**Issue by koretskiyav** [wix-incubator/unidriver#14]
When i trying to take the `data-hook` attribute through the puppeteer unidriver its returns empty string. The same through the react unidriver works correctly. See example below:
```javascript
const hook = await base.$("[data-hook='app']").attr('data-hook');
console.log(hook); // puppeteer - '', react - 'app'
```

**Comment by GabiGrin** [comment]
@koretskiyav  just saw it.
Putting aside that I think `data-hook` is an anti-pattern, this sounds like a bug that needs addressing.

Are you up for helping with this? 🙄

**Comment by GabiGrin** [comment]
fixed in latest version
