### ISSUE TITLE
Feature request: query elements from the body

### ISSUE THREAD

**Issue by yardnsm** [wix-incubator/unidriver#16]
It's a common practice to query elements that exists outside of the rendered component (UniDriver's `base`), like portal.

For instance, I needed to implement a `clickOutside` method. In a "vanilla" driver it could be written like this:

```js
// ...

    /** Click outside of the component */
    clickOutside: () => document.dispatchEvent(new Event('mousedown')),

// ...
```

It would be awesome to have an option to query elements from the top level element (and also access it). Since `base` refers to a container, a suggested approach is to expose a function from the `unidriver` module directly:

```typescript
import { $ } from 'unidriver';

const popoverDriver = (base: UniDriver) => {
	return {
		clickOnPortal: async () => $('.some-portal').click()
	};
};
```

Or may to pass it directly to the driver:

```typescript
const popoverDriver = (base: UniDriver, $) => {
	return {
		clickOnPortal: async () => $('.some-portal').click()
	};
};
```

**Comment by GabiGrin** [comment]
Hi,
great points, added a long awaited FAQ section addressing that.

UniDriver hides the implementation and aims to do only what external users would do.
For example, click outside X means click on anything else other than the X. See this https://github.com/wix-incubator/unidriver#how-do-i-click-outside-mycomponent

In popovers, you must access it somehow, and the sanest way that will work for all platforms is to pass another unidriver that represents the "global element". See this https://github.com/wix-incubator/unidriver#how-do-i-use-it-with-a-portaled-elements-ie-popovers-modals

Let me know if this makes sense and feel free to feedback / PR on the FAQ

**Comment by yardnsm** [comment]
Looks good, thanks! 😄
