### ISSUE TITLE
"react" adapter is probably a wrong name

### ISSUE THREAD

**Issue by GabiGrin** [wix-incubator/unidriver#19]
I feel that calling the adapter used in react/jsdom "react" is wrong:
1. the only reason it's "react" is because it uses Simulate when needed. 
2. you can build a react app and test it with puppeteer, it doesn't make the puppeteer driver a "react" one.

I think `jsdom` is a more suitable name, but then I am still not sure how to express the framework specific quirks (like `Simulate` for react, and who knows what for others).  Maybe it's jsdom + plugin? who knows?

@ophirg  what do you think? @shlomitc?

**Comment by shlomitc** [comment]
Will this react adapter be the same also if you run the test in karma? If yes, then jsdom might not be the right name for it.
Maybe it’s a combination of both the platform and the framework you use?

**Comment by GabiGrin** [comment]
@shlomitc it depends on if karma is connected to jsdom or to a real browser. if it's jsdom then it's the same as mocha. if it's PhantomJS (🤷‍♂️ ) it might be a different thing and if it's connected to Chrome headless via karma it will be a third thing.
Maybe they are all "DOM" adapters with special quirks (all in JSDOM will not have measuring, React in all will need Simulate if not connected to body, PhantomJS will probably be weird on it's own).

maybe "dom" adapter is the right one? with possible combinations of frameworks / platform quirks

**Comment by GabiGrin** [comment]
fixed by #37
