### ISSUE TITLE
Make a separate entry file for each type of driver

### ISSUE THREAD

**Issue by shlomitc** [wix-incubator/unidriver#2]
Currently, all drivers are imported from the same index file as seen here:
https://github.com/wix-incubator/unidriver/blob/master/src/index.ts#L1

This means that importing this file in one of the technologies will import others as well.
So if I'm using only `enzyme` for example and not using `puppeteer` I will be forced to install also the later as it is not tree-shaked in node.

I suggest something like:
`import {reactUniDriver} from 'unidriver/react'`
`import {puppeteerUniDriver} from 'unidriver/puppeteer'`
etc...

**Comment by GabiGrin** [comment]
@shlomitc isn't "react" the only one exported in this case? while puppeteer/selenium are inside "lib", they are not exported from it and require explicit imports
Regardless, I wanted to get rid of the react one too so thanks :)

**Comment by shlomitc** [comment]
You’re right. Only React is exported there.
So how other are consumed? Directly from the dist folder? If so, creating an entry is still needed

**Comment by GabiGrin** [comment]
Yep, and #7  will help with that ⭐️
