### ISSUE TITLE
`click` in react adapter should also emit mouseDown and mouseUp events

### ISSUE THREAD

**Issue by GabiGrin** [wix-incubator/unidriver#32]
use case: a component listens to `mouseDown` and not `click. In react the tests that use `click` will fail but in other adapters it won't
this is because in real browsers, when you click, you get both click events and mouse events.

thus, I think that `click` in the react adapter should also emit `mouseUp` and `mouseDown` events

**Comment by hepiyellow** [comment]
Just to emphasise this is a JSDOM issue (not react)

And  `click()` should also trigger a `focus` event

**Comment by hepiyellow** [comment]
@GabiGrin 
I think that JSDOM deserves its own adapter. 
And that there should be also a "regular" `react` adapter (NO JSDOM), with which you don't need to simulate `focus` when an input is clicked.

**Comment by hepiyellow** [comment]
@GabiGrin @borisd9 Is this WIP? When is it due?

**Comment by hepiyellow** [comment]
@GabiGrin @borisd9 Should I make a PR on this, or are you working on it?

**Comment by hepiyellow** [comment]
@GabiGrin @borisd9 We need this?
Are you on it, or should I make a PR?

Are you sure about agreeing to add this? (Before I make the PR)

**Comment by hepiyellow** [comment]
@GabiGrin Where should we document stuff like this?
That in `react` adapter, it also simulates `mouseDown` and `mouseUp`?
I think this should be documented.
But I don't feel that it should be documented in the `core.

How would you go about adding method-specific docs in the adapters?

**Comment by hepiyellow** [comment]
@GabiGrin Would this be a breaking change?
