### ISSUE TITLE
`exists()` swallows `Found [n > 1] elements...` error

### ISSUE THREAD

**Issue by hepiyellow** [wix-incubator/unidriver#41]
In general,
I don't understand why `exists()` shuold swallow ALL errors [(like so)](https://github.com/wix-incubator/unidriver/blob/ac0e51a2ed0027de8f56b99f2d0c3d5006026ec7/adapters/jsdom-react/src/index.ts#L59).

But a particularly important error which is swallowed is when we use `$` and it returns more than 1 element.

For example:
```
$('.myClassName').exists()
```

If there is more than one element with `.myClassName`, the `exists()` will return false, and no error would be printed.

### Expected Behavior

Well, Protractor returns the first element found and prints a warning:

> WARNING - more than one element found for locator By.cssSelector(".myClassName") - the first result will be used

If you wantbe strict and throw Error, thats fine by me.
But having `exists()` return false in this case, is a mistake I think. 

So I labeled this as a BUG.
And also added a label API, since this affects the way that tests are written.

**Comment by GabiGrin** [comment]
Interesting, nice catch
Given a selector and its existence, there are 3 possible cases: 
- only 1 exists, easily `true`
- no such element exists, probably `false`
- more than 1 element exists - here's the hard question. It obviously exists, but for our purposes it doesn't fit. Returning `true` will be also misleading. 

Throwing an error does add a 3rd branch to to this method, which is something I dislike, but it still sounds like the best alternative.

@borisd9  thoughts?

**Comment by GabiGrin** [comment]
ok fixing this was interesting, good catch @hepiyellow  :)

**Comment by hepiyellow** [comment]
So what is your fix?
To throw an error (when multiple occurences are found)?
OR to return the first, and issue a console.warn (or console.error)

**Comment by GabiGrin** [comment]
Throw an error. The error comes from `core` and is part of the spec (validated in test suite)

https://github.com/wix-incubator/unidriver/blob/e853f43b2c00d85bfedb792f445027a3b2c7868d/adapters/jsdom-react/src/index.ts#L71
