### ISSUE TITLE
`jsdom-react`: Dispatching REAL events get `nulllified`  by React

### ISSUE THREAD

**Issue by hepiyellow** [wix-incubator/unidriver#43]
If I am not mistaken, the issue with dispatching real events (like it is done in [`click()`](https://github.com/wix-incubator/unidriver/blob/ac0e51a2ed0027de8f56b99f2d0c3d5006026ec7/adapters/jsdom-react/src/index.ts#L101)), is that because the `dispatchEvent()` is async (if I am not mistaken), then React's Synthetic event optimization, nullifies the event (sets ALL event properties to null).

This means that a `change` event would have `event.target == null`.

JSDOM consumers (Which use React's `Simulate`) are used to be able to assert, for example, on `event.target.value` when testing an `onChange` event listener.

I think that for this adapter, which is now defined as `jsdom-react`, there should be NO dispatching of REAL event. Only Simulated (Simulating events is sync).

**Comment by hepiyellow** [comment]
@GabiGrin @borisd9 ping?

**Comment by GabiGrin** [comment]
Agreed

**Comment by GabiGrin** [comment]
will be fixed in #56
