### ISSUE TITLE
BUG : `exists()` returns true by mistake

### ISSUE THREAD

**Issue by hepiyellow** [wix-incubator/unidriver#45]
### The Symptom

Assuming there are no elements with `.someClass`
```js
const first = await driver.$$('.someClass').get(0);
first.exists(); // Returns true
first.getNative(); // Returns undefined
```

### The Bug

`$$` calls `jsdomReactUniDriverList( ()=> Promise.resolve([]))` - [(here)](https://github.com/wix-incubator/unidriver/blob/0f5a669db352f1093eac86255a63d4adee1674e2/adapters/jsdom-react/src/index.ts#L83)

`get(0)` - `cont` is an empty array ([here](https://github.com/wix-incubator/unidriver/blob/0f5a669db352f1093eac86255a63d4adee1674e2/adapters/jsdom-react/src/index.ts#L21))

Then in `exists()` , `elem()` returns `undefined` (since `[][0]` is undefined), and no error is thrown, `exists` returns true.

**Comment by GabiGrin** [comment]
good catch ⭐️ 
will fix

**Comment by GabiGrin** [comment]
fixed and test case added to the test suite
