### ISSUE TITLE
API Discussion: `getNative()` should not throw error

### ISSUE THREAD

**Issue by hepiyellow** [wix-incubator/unidriver#46]
If I am implementing a driver method that returns the native element.
```js
  getSomeElement: ()=> base.$('.someClass').getNative();
```

This will throw an error if `.someClass` is not found.
which is not a very good API for the driver.
INconvenient for a test that might expect `getSomeElement()` to not find anything.
Which meanswe need to expose another method:
```js
  isSomeElementExists: ()=> base.$('.someClass').exists();
```

### Workaround

My driver can use a `safeGetNative`
```js
export async function safeGetNative<T>(base: UniDriver<T>) {
  return (await base.exists()) ? base.getNative() : null;
}

  getSomeElement: ()=> safeGetNative(base.$('.someClass'));
```

### Question

What is the benefit of having `getNative()` throw an error?

**Comment by GabiGrin** [comment]
I'm not a fan of throwing errors, but not a fan of `null` either. 
Ideally it would be `getNative() => Promise<Maybe<T>>` 🤓 

As the library goes with throwing errors for when elements are not found, I feel that throwing an error here is consistent as well.

I think your workaround is fair enough and should be the recommended solution for users who find the error throwing a problem
