### ISSUE TITLE
Where is the Legacy branch (before split to packages) ?

### ISSUE THREAD

**Issue by hepiyellow** [wix-incubator/unidriver#48]
Is there a branch with the legacy code before splitting to packages?
For those who are still using:
```
 unidriver: ^2.0.0
```

If there is no branch, what is the latest Tag ?

**Comment by GabiGrin** [comment]
no, but if needed we can add it
the latest tag is this https://github.com/wix-incubator/unidriver/releases/tag/v2.0.1
