### ISSUE TITLE
Migration Docs - from old `unidrvier 2.x` to `@unidriver/xxxx`

### ISSUE THREAD

**Issue by hepiyellow** [wix-incubator/unidriver#59]
Hi,

Are there any breaking changes when upgrading from `unidriver` 2.x
to `@unidriver/xxx`?

If so, a Migration doc would be useful.

**Comment by hepiyellow** [comment]
@GabiGrin @borisd9 Are there any breaking changes?

**Comment by borisd9** [comment]
@hepiyellow each adapter now has its own package. But the adapters API has only added more methods - so no breaking changes in the API. You will just need to update your imports

**Comment by hepiyellow** [comment]
Great News. Thanks !

**Comment by hepiyellow** [comment]
@borisd9 
So breaking changes I know about are:

| method | `unidriver@2.0.1` | `@unidriver/* latest` |
|-----------|-------------------|---------------------| 
| pupUniDriver |  `(el: ElementGetter): UniDriver<ElementHandle>`     |   `(    el: ElementGetter \| BaseElementContainer): UniDriver<ElementContainer>`   |
|reactUniDriver  |  `reactUniDriver` | `jsdomReactUniDriver`|
| `attr` | `(name: string) => Promise<string>;` | `(name: string) => Promise<string \| null>` |

**Comment by borisd9** [comment]
You're right, it seems that this was added before the move but didnt get published.
I'll add this to the readme

**Comment by hepiyellow** [comment]
@borisd9 I added another breaking change to the table

**Comment by borisd9** [comment]
@hepiyellow i dont see its throwing error now..  its returning `false` without any element not found errors. Can you re-check? provide example?
i think you have a typo in the previous version description.

**Comment by hepiyellow** [comment]
@borisd9 Nevermind, I didn't mean that it throws an error,
I remembered something about it throwing an error internally in the jsdom-react adapter.
And that, that error is catched, and false is returned.

**Comment by borisd9** [comment]
👍  closing this one

**Comment by hepiyellow** [comment]
@borisd9 
The `$$(selector).get()` is not throwing an error, but it is a breaking change that should appear in the Migration docs. Please add it.
