### ISSUE TITLE
protractor: connect to test suite

### ISSUE THREAD

**Issue by GabiGrin** [wix-incubator/unidriver#62]
@shlomitc I remember that you guys added this adapter
Can someone help with this? the adapter was not connected to the test suite

**Comment by shlomitc** [comment]
@hepiyellow - can you please assist?

**Comment by hepiyellow** [comment]
@GabiGrin Is this related to https://github.com/wix-incubator/unidriver/issues/60 ?

**Comment by GabiGrin** [comment]
fixed in #69
